title: Eric Li # your name (or website title) here
logo: "/images/profile_pic3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Statistics and Data Science Student at the 
  University of Maryland - College Park
  <br><br>
  <a href="/about_me.md">About Me</a>
  <br><br>
  <a href="/EricLi_Resume_Final.pdf">CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/eric-li-574626203/">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-M8ZDS4FQ21 # your Google Analytics tracking ID here
